[project]
name = "soundscape-app"
version = "0.1.0"
description = "An interactive visualization app for soundscape datasets"
authors = [
    { name="Fabian Rosenthal", email="rosenthal.fabian@gmail.com" }
]

[project.dependencies]
bokeh = "==3.5.2"
numpy = ">=2.1.1"
pandas = ">=2.2.2"